In [7]:
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.8,shuffle=False)
X_train

array([[0, 1]])

In [20]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(["paris", "paris", "tokyo", "amsterdam"])
le.transform(["tokyo", "tokyo", "paris"])

array([2, 2, 1])

In [67]:
from sklearn import preprocessing
import numpy as np
X_train = np.array([[ 1],
                    [ 2],
                    [ 0]])
scaler = preprocessing.MinMaxScaler().fit(X_train)
scaler

MinMaxScaler()

In [68]:
X_scaled = scaler.transform(X_train)
X_scaled

array([[0.5],
       [1. ],
       [0. ]])

In [69]:

# importing the required libraries
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
  
# creating a dataframe for example
pd_data = pd.DataFrame({
    "Item": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Price": [100, 300, 250, 120, 910, 345, 124, 1000, 289, 500]
})
  
# Creating an instance of the sklearn.preprocessing.MinMaxScaler()
scaler = MinMaxScaler()
  
# Scaling the Price column of the created dataFrame and storing
# the result in ScaledPrice Column
pd_data[["ScaledPrice"]] = scaler.fit_transform(pd_data[["Price"]])
  
print(pd_data)

   Item  Price  ScaledPrice
0     1    100     0.000000
1     2    300     0.222222
2     3    250     0.166667
3     4    120     0.022222
4     5    910     0.900000
5     6    345     0.272222
6     7    124     0.026667
7     8   1000     1.000000
8     9    289     0.210000
9    10    500     0.444444


In [70]:
pd_data[["Price"]]

Price
0    100
1    300
2    250
3    120
4    910
5    345
6    124
7   1000
8    289
9    500

In [79]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6],[0, 15, 2]])

print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 0 15  2]]


In [84]:
scaler = preprocessing.MinMaxScaler().fit(arr)

In [81]:
X_scaled = scaler.transform(arr)
X_scaled

array([[0.25      , 0.        , 0.25      ],
       [1.        , 0.23076923, 1.        ],
       [0.        , 1.        , 0.        ]])